### PR TITLE
MAR.PDF

### PR DESCRIPTION
**Pull request by PrometheusInscription**

### CODE REVIEW

**Review by Sagardas112 — APPROVED** [review]

**Comment by Sagardas112** [comment]
0xFf76358446A7Bd039821cf41A567e4B5C289cc0f

**Comment by Baro1905** [comment]
0x48618426fBb5Ec333102deA5a3d812130D26b8D9

**Comment by Baro1905** [comment]
https://github.com/TechRate/Smart-Contract-Audits/pull/16/commits/9848be183cd3a1803a78d6b9c093be942f8aea75

**Comment by Baro1905** [comment]
9848be1

**Review by Baro1905 — APPROVED** [review]

**Review by Baro1905 — CHANGES_REQUESTED** [review]
gh pr checkout 16

**Comment by Mohsen-Phoenix** [comment]
0x10627985Da14fe875Ad3A9A44C3f0b2aA65749da

**Review by Mohsen-Phoenix — CHANGES_REQUESTED** [review]
``0x10627985Da14fe875Ad3A9A44C3f0b2aA65749da

**Comment by Mohsen-Phoenix** [comment]
``0x10627985Da14fe875Ad3A9A44C3f0b2aA65749da

**Review by Mohsen-Phoenix — COMMENTED** [review]
0x10627985Da14fe875Ad3A9A44C3f0b2aA65749da

**Review by Mohsen-Phoenix — APPROVED** [review]
0x10627985Da14fe875Ad3A9A44C3f0b2aA65749da

**Review by Mohsen-Phoenix — CHANGES_REQUESTED** [review]
0x10627985Da14fe875Ad3A9A44C3f0b2aA65749da

**Review by Baro1905 — COMMENTED** [review]
0xdb5d32f98f177cf0da9f4e113769af9855fd405f

**Comment by Baro1905** [comment]
0xdb5d32f98f177cf0da9f4e113769af9855fd405f

**Pull request closed without merging**
